[chore/#166] GitHub Actions 구조 변경

diff --git a/.github/workflows/deploy-on-ubuntu-server.yml b/.github/workflows/deploy-on-ubuntu-server.yml
--- a/.github/workflows/deploy-on-ubuntu-server.yml
+++ b/.github/workflows/deploy-on-ubuntu-server.yml
@@ -11,15 +11,27 @@ on:
 jobs:
     # 첫번째 단계 : 빌드
     build:
-        runs-on: [self-hosted, gamechu-server]
+        runs-on: ubuntu-latest
+
+        env:
+            DATABASE_URL: ${{ secrets.DATABASE_URL }}
+            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
+            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
+            SOCKET_SERVER_URL: ${{ secrets.SOCKET_SERVER_URL }}
 
         steps:
             - name: Build Next.js Project
-              run: npx prisma generate
+              run: |
+                  set -e
+                  cd ~/www/gamechu || { echo "Failed to change working directory"; exit 1; }
+                  git pull origin dev || { echo "Failed to git pull"; exit 1; }
+                  npx prisma generate || { echo "Failed to generate via prisma client"; exit 1; }
+                  npm ci || { echo "Failed to install dependencies"; exit 1; }
+                  npm run build || { echo "Failed to build"; exit 1; }
 
     # 두번째 단계: 테스트
     test:
-        runs-on: [self-hosted, gamechu-server]
+        runs-on: ubuntu-latest
 
         steps:
             - name: Test Next.js Project
@@ -27,9 +39,16 @@ jobs:
 
     # 세번째 단계: 배포
     deploy:
-        needs: build
+        needs: [build, test]
+
         runs-on: [self-hosted, gamechu-server]
+
+        env:
+            DATABASE_URL: ${{ secrets.DATABASE_URL }}
+            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
+            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
+            SOCKET_SERVER_URL: ${{ secrets.SOCKET_SERVER_URL }}
 
         steps:
             - name: Deploy Next.js Project
-              run: /home/gamechu/www/gamechu/next-app-update.sh
+              run: /home/gamechu/www/gamechu/next-app-deploy.sh
